Merge and PCA of the pooled watermelon count matrix and the pooled wa…
meyer-lab/barcoded-Pf2 pull request #7
Opened 2024-09-09 19:01 UTC by quinn-mccall

…termelon data matrix.

2024-09-10 20:20 UTC, aarmey requested changes
Can you please make both of these Python functions, and then move them to `imports.py`?

2024-10-10 03:45 UTC, quinn-mccall commented
Hi Dr. Meyer! I just added the function to imports.py and called it and wrote assertions for it in tests.py, let me know what you think!

2024-10-12 23:20 UTC, aarmey requested changes
Thanks @quinn-mccall! I made some small adjustments, including updating the file paths so that this runs on Aretha. Please see my comment about speeding this up.

2024-10-12 23:20 UTC, aarmey commented on pf2barcode/imports.py
> +    data.obs = data.obs.join(columns, how="left")
After this line, could you use `data.write("filename")` with each file to create an anndata file of each dataset? This long importing will quickly get tiring, so we should just store the datasets as an anndata file. If you save them on your account on Aretha, I can then move them somewhere where everyone can access.

2024-10-27 16:11 UTC, aarmey approved these changes
@quinn-mccall this did turn out to be trickier than I expected. I have set up the files, and you should find that this is much faster now.

2024-10-27 16:11 UTC, merged